[build]
builder = "NIXPACKS"
buildCommand = "go build -o bin/server cmd/web/main.go"

[deploy]
startCommand = "./bin/server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
installCommand = "go mod download"
buildCommand = "go build -o bin/server cmd/web/main.go"
startCommand = "./bin/server"
