[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd cmd/web && go run main.go"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
buildCommand = "go build -o bin/server cmd/web/main.go"
startCommand = "./bin/server"

